### ISSUE TITLE
`make install` error

### ISSUE THREAD

**Issue by TMTBO** [tami5/xbase#68] opened 2022-06-10 07:41 UTC
Hello, does it work for now? I got an error when execute `make install`.
```
make install
    Updating git repository `https://github.com/tami5/simctl`
    Updating crates.io index
  Downloaded ppv-lite86 v0.2.16
  Downloaded itertools v0.10.3
  Downloaded regex v1.5.6
  Downloaded strum v0.24.0
  Downloaded nom-supreme v0.6.0
  Downloaded shell-words v1.1.0
  Downloaded strum_macros v0.24.0
  Downloaded tracing v0.1.34
  Downloaded anyhow v1.0.57
  Downloaded async-stream v0.3.3
  Downloaded rand_core v0.5.1
  Downloaded rustversion v1.0.6
  Downloaded ryu v1.0.10
  Downloaded matches v0.1.9
  Downloaded num_cpus v1.13.1
  Downloaded aho-corasick v0.7.18
  Downloaded thiserror-impl v1.0.31
  Downloaded async-stream-impl v0.3.3
  Downloaded dirs v4.0.0
  Downloaded brownstone v1.1.0
  Downloaded async-trait v0.1.53
  Downloaded const_format_proc_macros v0.2.22
  Downloaded getrandom v0.1.16
  Downloaded bsp-types v0.1.3
  Downloaded matchers v0.1.0
  Downloaded joinery v2.1.0
  Downloaded rand v0.7.3
  Downloaded parity-tokio-ipc v0.9.0
  Downloaded xcodebuild v0.1.6
  Downloaded tokio-macros v1.7.0
  Downloaded same-file v1.0.6
  Downloaded arrayvec v0.7.2
  Downloaded futures-task v0.3.21
  Downloaded ansi_term v0.12.1
  Downloaded serde_yaml v0.8.24
  Downloaded tinyvec v1.6.0
  Downloaded sharded-slab v0.1.4
  Downloaded bitflags v1.3.2
  Downloaded cfg-if v1.0.0
  Downloaded futures-sink v0.3.21
  Downloaded futures-core v0.3.21
  Downloaded time v0.3.9
  Downloaded futures v0.3.21
  Downloaded log v0.4.17
  Downloaded crossbeam-utils v0.8.8
  Downloaded url v2.2.2
  Downloaded crossbeam-channel v0.5.4
  Downloaded wax v0.4.0
  Downloaded lsp-types v0.93.0
  Downloaded indent_write v2.2.0
  Downloaded tracing-core v0.1.26
  Downloaded form_urlencoded v1.0.1
  Downloaded autocfg v1.1.0
  Downloaded tap v1.0.1
  Downloaded percent-encoding v2.1.0
  Downloaded lazy_static v1.4.0
  Downloaded dirs-sys v0.3.7
  Downloaded either v1.6.1
  Downloaded heck v0.4.0
  Downloaded futures-macro v0.3.21
  Downloaded num_threads v0.1.6
  Downloaded futures-executor v0.3.21
  Downloaded linked-hash-map v0.5.4
  Downloaded nom v7.1.1
  Downloaded mio v0.8.3
  Downloaded bytes v1.1.0
  Downloaded unicode-ident v1.0.0
  Downloaded futures-channel v0.3.21
  Downloaded indexmap v1.8.1
  Downloaded futures-util v0.3.21
  Downloaded serde v1.0.137
  Downloaded regex-automata v0.1.10
  Downloaded const_format v0.2.23
  Downloaded minimal-lexical v0.2.1
  Downloaded itoa v1.0.2
  Downloaded once_cell v1.12.0
  Downloaded pin-utils v0.1.0
  Downloaded pin-project-lite v0.2.9
  Downloaded proc-macro2 v1.0.39
  Downloaded quote v1.0.18
  Downloaded slab v0.4.6
  Downloaded memchr v2.5.0
  Downloaded rand_chacha v0.2.2
  Downloaded futures-io v0.3.21
  Downloaded serde_repr v0.1.8
  Downloaded serde_json v1.0.81
  Downloaded signal-hook-registry v1.4.0
  Downloaded serde_derive v1.0.137
  Downloaded pori v0.0.0
  Downloaded syn v1.0.95
  Downloaded socket2 v0.4.4
  Downloaded tokio-stream v0.1.8
  Downloaded tinyvec_macros v0.1.0
  Downloaded thread_local v1.1.4
  Downloaded derive-deref-rs v0.1.1
  Downloaded thiserror v1.0.31
  Downloaded smallvec v1.8.0
  Downloaded unicode-bidi v0.3.8
  Downloaded bsp-server v0.1.3
  Downloaded process-stream v0.2.2
  Downloaded hashbrown v0.11.2
  Downloaded regex-syntax v0.6.26
  Downloaded idna v0.2.3
  Downloaded bstr v0.2.17
  Downloaded tracing-subscriber v0.3.11
  Downloaded yaml-rust v0.4.5
  Downloaded tracing-log v0.1.3
  Downloaded unicode-normalization v0.1.19
  Downloaded tracing-attributes v0.1.21
  Downloaded walkdir v2.3.2
  Downloaded tracing-appender v0.2.2
  Downloaded unicode-xid v0.2.3
  Downloaded tokio v1.18.2
  Downloaded libc v0.2.126
  Downloaded 114 crates (6.4 MB) in 12.02s
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.0
   Compiling syn v1.0.95
   Compiling libc v0.2.126
   Compiling memchr v2.5.0
   Compiling cfg-if v1.0.0
   Compiling lazy_static v1.4.0
   Compiling pin-project-lite v0.2.9
   Compiling futures-core v0.3.21
   Compiling log v0.4.17
   Compiling serde_derive v1.0.137
   Compiling once_cell v1.12.0
   Compiling futures-task v0.3.21
   Compiling serde v1.0.137
   Compiling regex-syntax v0.6.26
   Compiling futures-channel v0.3.21
   Compiling itoa v1.0.2
   Compiling futures-util v0.3.21
   Compiling tinyvec_macros v0.1.0
   Compiling getrandom v0.1.16
   Compiling futures-sink v0.3.21
   Compiling futures-io v0.3.21
   Compiling matches v0.1.9
   Compiling crossbeam-utils v0.8.8
   Compiling pin-utils v0.1.0
   Compiling slab v0.4.6
   Compiling unicode-bidi v0.3.8
   Compiling bytes v1.1.0
   Compiling serde_json v1.0.81
   Compiling anyhow v1.0.57
   Compiling ryu v1.0.10
   Compiling percent-encoding v2.1.0
   Compiling minimal-lexical v0.2.1
   Compiling ppv-lite86 v0.2.16
   Compiling autocfg v1.1.0
   Compiling rustversion v1.0.6
   Compiling smallvec v1.8.0
   Compiling async-trait v0.1.53
   Compiling arrayvec v0.7.2
   Compiling unicode-xid v0.2.3
   Compiling bitflags v1.3.2
   Compiling ansi_term v0.12.1
   Compiling joinery v2.1.0
   Compiling linked-hash-map v0.5.4
   Compiling heck v0.4.0
   Compiling same-file v1.0.6
   Compiling either v1.6.1
   Compiling indent_write v2.2.0
   Compiling hashbrown v0.11.2
   Compiling tap v1.0.1
   Compiling shell-words v1.1.0
   Compiling tracing-core v0.1.26
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.4
   Compiling tinyvec v1.6.0
   Compiling form_urlencoded v1.0.1
   Compiling indexmap v1.8.1
   Compiling brownstone v1.1.0
   Compiling walkdir v2.3.2
   Compiling yaml-rust v0.4.5
   Compiling itertools v0.10.3
   Compiling regex-automata v0.1.10
   Compiling tracing-log v0.1.3
   Compiling unicode-normalization v0.1.19
   Compiling aho-corasick v0.7.18
   Compiling nom v7.1.1
   Compiling matchers v0.1.0
   Compiling bstr v0.2.17
   Compiling quote v1.0.18
   Compiling mio v0.8.3
   Compiling num_cpus v1.13.1
   Compiling signal-hook-registry v1.4.0
   Compiling socket2 v0.4.4
   Compiling num_threads v0.1.6
   Compiling dirs-sys v0.3.7
   Compiling crossbeam-channel v0.5.4
   Compiling idna v0.2.3
   Compiling regex v1.5.6
   Compiling const_format_proc_macros v0.2.22
   Compiling rand_core v0.5.1
   Compiling pori v0.0.0
   Compiling nom-supreme v0.6.0
   Compiling time v0.3.9
   Compiling dirs v4.0.0
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling const_format v0.2.23
   Compiling futures-macro v0.3.21
   Compiling tracing-attributes v0.1.21
   Compiling tokio-macros v1.7.0
   Compiling thiserror-impl v1.0.31
   Compiling serde_repr v0.1.8
   Compiling async-stream-impl v0.3.3
   Compiling strum_macros v0.24.0
   Compiling derive-deref-rs v0.1.1
   Compiling async-stream v0.3.3
   Compiling tokio v1.18.2
   Compiling thiserror v1.0.31
   Compiling wax v0.4.0
   Compiling tracing v0.1.34
   Compiling strum v0.24.0
   Compiling tracing-subscriber v0.3.11
   Compiling tracing-appender v0.2.2
   Compiling futures-executor v0.3.21
   Compiling tokio-stream v0.1.8
   Compiling futures v0.3.21
   Compiling process-stream v0.2.2
   Compiling parity-tokio-ipc v0.9.0
   Compiling xcodebuild v0.1.6
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/xpeng/.cargo/registry/src/github.com-1ecc6299db9ec823/xcodebuild-0.1.6/src/lib.rs:2:12
  |
2 | #![feature(str_split_whitespace_as_str)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling url v2.2.2
For more information about this error, try `rustc --explain E0554`.
error: could not compile `xcodebuild` due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [install] Error 101
```

**Comment by tami5** [comment] 2022-06-10 12:53
Uh it requires nightly release of rust, but that's unintended requirement. I will make sure it builds on stable release. Thanks for reporting

**Comment by akinsho** [comment] 2022-06-10 20:03
@tami5 apologies for posting on this closed issue, but I'm seeing issues as well with running make install. Primarily, `xcodebuild` can't be found. As far as I can tell this is your library you wrote for this and is only available on GitHub right?
```
➜ make install                                                           22:01:51
    Updating crates.io index
error: no matching package named `xcodebuild` found
location searched: registry `crates-io`
```
Am I supposed to do something to allow it to be fetched during the make call?

**Comment by tami5** [comment] 2022-06-10 21:27
> @tami5 apologies for posting on this closed issue, but I'm seeing issues as well with running make install. Primarily, `xcodebuild` can't be found. As far as I can tell this is your library you wrote for this and is only available on GitHub right?
> 
> ```
> ➜ make install                                                           22:01:51
>     Updating crates.io index
> error: no matching package named `xcodebuild` found
> location searched: registry `crates-io`
> ```
> 
> Am I supposed to do something to allow it to be fetched during the make call?

Oh @akinsho, no worries, my apologies I the version is wrong, it needs to be 0.1.8 instead of 0.1.7 that's why it's isn't found in crates.io. pushing a fix rn

Thanks a lot @akinsho

**Comment by akinsho** [comment] 2022-06-10 21:58
I'm still hitting this issue unfortunately on the latest commit

**Comment by tami5** [comment] 2022-06-10 22:13
🤔  that's odd https://crates.io/crates/xcodebuild/versions is published.

try cargo update.

**Comment by akinsho** [comment] 2022-06-10 23:08
I think maybe another dependency might need to be updated as well `simctl`?
```
➜ cargo update                                                            1:07:18
    Updating crates.io index
    Updating git repository `https://github.com/tami5/simctl`
error: no matching package named `xcodebuild` found
location searched: registry `crates-io`
required by package `xbase v0.1.0 (~/.local/share/nvim/site/pack/packer/opt/xbase)`
````

**Comment by tami5** [comment] 2022-06-10 23:16
@akinsho  🤔 simctl is directly cloning from my fork of simctl as specified in cargo.toml and it doesn't depend on xcodebuild at all. 

That must be some weird issue with crates.io, could you try changing line 92 in Cargo.toml from

```toml
xcodebuild            = { version  = "0.1.8", optional = true, features = ["tracing"] }
```

to 

```toml
xcodebuild            = { git = "https://github.com/tami5/xcodebuild", optional = true, features = ["tracing"] }
```

**Comment by akinsho** [comment] 2022-06-11 06:59
```
➜ make install                                                                                                                                                               8:58:31
    Updating git repository `https://github.com/tami5/xcodebuild`
error: failed to get `xcodebuild` as a dependency of package `xbase v0.1.0 (/Users/akin/.local/share/nvim/site/pack/packer/opt/xbase)`

Caused by:
  failed to load source for dependency `xcodebuild`

Caused by:
  Unable to update https://github.com/tami5/xcodebuild

Caused by:
  failed to parse manifest at `/Users/akin/.cargo/git/checkouts/xcodebuild-4c1e65814fc5ca94/d83797e/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
make: *** [install] Error 101
```
Is what I get running that command

**Comment by TMTBO** [comment] 2022-06-11 10:09
> Uh it requires nightly release of rust, but that's unintended requirement. I will make sure it builds on stable release. Thanks for reporting

Yeah, I have make it success. Thanks very much.
But now, I got a new problem, when I execute `Watch`, `Run` or  `Build`.  `vim.loop.cwd()` always got `nil`.
```
E5108: Error executing lua .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:57: No project info found
stack traceback:
        [C]: in function 'error'
        .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:57: in function 'get_selections'
        .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:154: in function 'watch'
        .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:215: in function 'run_replace_or_original'
        ...im-telescope/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...nvim-telescope/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

xbase-daemon.log
```
2022-06-11T10:07:39.476883Z  INFO xbase::daemon::requests::drop: Drop(29469: Project_ToScanner)
2022-06-11T10:07:39.476924Z  INFO xbase::store::projects: [Projects] remove("Project_ToScanner")
2022-06-11T10:07:39.476938Z  INFO xbase::store::watcher: [Watcher] remove("Project_ToScanner")
2022-06-11T10:07:39.476957Z DEBUG xbase::store::clients: [Clients] remove(29469)
2022-06-11T10:07:39.476972Z  INFO xbase::state: Syncing state to all nvim instance
2022-06-11T10:07:42.609978Z  INFO xbase::store::clients: [Clients] add(31167)
2022-06-11T10:07:42.639041Z  INFO xbase::store::projects: [Projects] add(Project_ToScanner)
2022-06-11T10:07:42.654594Z  INFO xbase::store::watcher: [Watcher] add("Project_ToScanner")
2022-06-11T10:07:43.063669Z ERROR xcodebuild::parser::manual: Skipping: 2022-06-11
2022-06-11T10:07:43.618145Z ERROR xcodebuild::parser::manual: Skipping: Resolved
2022-06-11T10:07:43.767677Z ERROR xcodebuild::parser::manual: Skipping: **
2022-06-11T10:07:44.493449Z ERROR xcodebuild::runner: Fail to parse step Fail to parse compilation step `Trying to overwrite set path with -import-objc-header`
2022-06-11T10:07:48.792637Z ERROR xcodebuild::parser::manual: Skipping: /Users/xpeng/Project/ToScanner/ToScanner/Main/MainViewController.swift:9:8:
2022-06-11T10:07:48.793279Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.793641Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.793991Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.794457Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.794867Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.795060Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.795237Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
2022-06-11T10:07:48.795423Z ERROR xcodebuild::runner: Fail to parse step Unexpected EOF while trying to parse `CompileSwift`, key: `CompileSwift`
```

**Comment by tami5** [comment] 2022-06-11 11:46
> > Uh it requires nightly release of rust, but that's unintended requirement. I will make sure it builds on stable release. Thanks for reporting
> 
> 
> 
> Yeah, I have make it success. Thanks very much.
> 
> But now, I got a new problem, when I execute `Watch`, `Run` or  `Build`.  `vim.loop.cwd()` always got `nil`.
> 
> ```
> 
> E5108: Error executing lua .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:57: No project info found
> 
> stack traceback:
> 
>         [C]: in function 'error'
> 
>         .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:57: in function 'get_selections'
> 
>         .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:154: in function 'watch'
> 
>         .../dein/repos/github.com/tami5/xbase/lua/xbase/pickers.lua:215: in function 'run_replace_or_original'
> 
>         ...im-telescope/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
> 
>         ...nvim-telescope/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
> 
>         [string ":lua"]:1: in main m

I see two separate issues here. first one, no project info, I have experienced it in the past, it doesn't happen often right? not sure why it happens so I need to track it.


The second issue, could you do 

```bash
xcodebuild clean build > build.log
```

in the project directory. I need to do tests on the parsing the build log, maybe apple changed something . 

Thanks

**Comment by tami5** [comment] 2022-06-11 11:48
> ```
> 
> ➜ make install                                                                                                                                                               8:58:31
> 
>     Updating git repository `https://github.com/tami5/xcodebuild`
> 
> error: failed to get `xcodebuild` as a dependency of package `xbase v0.1.0 (/Users/akin/.local/share/nvim/site/pack/packer/opt/xbase)`
> 
> 
> 
> Caused by:
> 
>   failed to load source for dependency `xcodebuild`
> 
> 
> 
> Caused by:
> 
>   Unable to update https://github.com/tami5/xcodebuild
> 
> 
> 
> Caused by:
> 
>   failed to parse manifest at `/Users/akin/.cargo/git/checkouts/xcodebuild-4c1e65814fc5ca94/d83797e/Cargo.toml`
> 
> 
> 
> Caused by:
> 
>   namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
> 
> make: *** [install] Error 101
> 
> ```
> 
> Is what I get after editing the cargo.toml

😕 more nightly related issues. Let me remove dep: syntax from xcodebuild toml file

**Comment by tami5** [comment] 2022-06-11 13:24
@TMTBO for the issue with log parsing, it turns out that my refactor of nightly stuff and replacement introduced the issue. it should work now, with recent commit.

@akinsho I believe it should work now, could you please retry.

**Comment by akinsho** [comment] 2022-06-11 13:30
@tami5 that worked 🎉, one thing to note though is that it changed my Cargo.lock
```diff
diff --git a/Cargo.lock b/Cargo.lock
index 75a34b8..6c1cee4 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1672,7 +1672,7 @@ checksum = "c811ca4a8c853ef420abd8592ba53ddbbac90410fab6903b3e79972a631f7680"
 
 [[package]]
 name = "xbase"
-version = "0.1.0"
+version = "0.1.2"
 dependencies = [
  "anyhow",
  "async-stream",
@@ -1710,9 +1710,9 @@ dependencies = [
 
 [[package]]
 name = "xcodebuild"
-version = "0.1.9"
+version = "0.1.10"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "747a42b03340a5b1c2b8c30ca7a5e9b1258c7428ed9ce9b1f233ea37a4c6588a"
+checksum = "3c97aaa241577daa45fbd798b716ce123174f29c61544d172d9e3250f394e6cb"
 dependencies = [
  "anyhow",
  "async-stream",
```
which will make updating after running make install fail in the future

**Comment by tami5** [comment] 2022-06-11 13:41
> that worked 🎉

🌟🌟🌟

> one thing to note though is that it changed my Cargo.lock which will make updating after running make install fail in the future

🤔 how so, isn't Cargo.lock needs to change when Cargo.toml changes, `make install` I believe shouldn't update Cargo.lock as it feeds from it, could you clarify

**Comment by akinsho** [comment] 2022-06-11 13:48
@tami5 I think the issue is that the `Cargo.lock` in the project hasn't had changes committed to it to represent the state that it should be in. I think you need to run make install on your end and commit the changes so that when I run make install on my side, it doesn't need to change the lock file. At least based on how lock files work in other languages.

**Comment by tami5** [comment] 2022-06-11 13:57
uhhh @akinsho I see what I mean. with each change to Cargo.toml I need to make sure I push Cargo.lock, (I just checked my end and sure enough Cargo.lock is left uncommitted). Thanks @akinsho I will make sure for future release to commit Cargo.lock changes

**Comment by akinsho** [comment] 2022-06-11 14:29
👍🏿 that's fixed now

**Closed** 2022-06-11 14:32 UTC

**Comment by TMTBO** [comment] 2022-06-12 03:03
> The second issue, could you do
> 
> ```shell
> xcodebuild clean build > build.log
> ```
> 
> in the project directory. I need to do tests on the parsing the build log, maybe apple changed something .

[build.log](https://github.com/tami5/xbase/files/8885117/build.log)

Yeah, I got the build.log now. Maybe it help.
Or should I create a new issue for this?

**Comment by tami5** [comment] 2022-06-12 11:29
> > The second issue, could you do
> > ```shell
> > xcodebuild clean build > build.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the project directory. I need to do tests on the parsing the build log, maybe apple changed something .
> 
> [build.log](https://github.com/tami5/xbase/files/8885117/build.log)
> 
> Yeah, I got the build.log now. Maybe it help.
> 
> And I got the error in xbase-daemon.log

Yah I will look into the build log in a bit. I do plan to do some progress on xcodebuild crate today.

> Or should I create a new issue for this?

Maybe if you experience more of no project info found, because this issue I've seen sometimes happen to me. But for logs parsing issues please open in  [xcodebuild](https://github.com/tami5/xcodebuild)

> ERROR xcodebuild::runner: Fail to parse step Fail to parse compilation step `Trying to overwrite set path with -import-objc-header`

The build logs as noted in the readme is controlled by [xcodebuild](https://github.com/tami5/xcodebuild) and it still under progress, this error is basically a debug message saying, hay parser, you didn't do anything with this line.

**Comment by tami5** [comment] 2022-06-13 01:00
> [build.log](https://github.com/tami5/xbase/files/8885117/build.log)

@TMTBO  it turned out that the reason the build failed is due to `Linker Duplicate Symbols Location`, I'm switching to regex match on xcodebuild and I was able to extract that `FlexLayoutYogaKit.o` and `FlexLayoutYoga.o`.

does this build okay with Xcode? maybe I'm missing some arguments with xcodebuild, idk

btw, the build logs was helpful in refining my matchers, thanks

**Comment by TMTBO** [comment] 2022-06-13 04:05
> > [build.log](https://github.com/tami5/xbase/files/8885117/build.log)
> 
> @TMTBO it turned out that the reason the build failed is due to `Linker Duplicate Symbols Location`, I'm switching to regex match on xcodebuild and I was able to extract that `FlexLayoutYogaKit.o` and `FlexLayoutYoga.o`.
> 
> does this build okay with Xcode? maybe I'm missing some arguments with xcodebuild, idk
> 
> btw, the build logs was helpful in refining my matchers, thanks

Yes, the `FlexLayout` is dumplicated. One for `SPM`, and another for `Pod`. And this work with Xcode.
